### ISSUE TITLE
PWM descriptor file for Mouse

### ISSUE THREAD

**Issue by ahorvath** [GreenleafLab/NucleoATAC#28]
Hi,
I would like to run NucleoATAC on mouse sample. Where can I get the PWM descriptor file?
Thanks!
Attila

**Comment by ahorvath** [comment]
Sorry I found the answer in a previous issue. I have another question. 

How can I make the nfr prediction more liberal?
Because I got ~5000 sites and I would like to have more potential nfr regions.

Thanks,
Attila

**Comment by AliciaSchep** [comment]
Hi Attila,
The current nfr prediction is very conservative as you have observed.  What this prediction is doing is identifying gaps between two called nucleosomes with low nucleosome occupancy-- this will miss nfrs where there isn't a sufficiently strong signal from a flanking nucleosome.  I am actively working on making a new version of the nfr prediction that will additionally predict nfrs without requiring flanking nucleosome signal.  I will post here when that update is available.  
-Alicia

**Comment by ahorvath** [comment]
Hi Alicia,

Ok, That's fine. I'm very satisfied with the result your program has produced. What I only want now is to create a meta plot for the distribution of the nucleosome positions relative to the summits of the newly appeared peaks upon a certain signal. Should I use the <SAMPLE>.occ.bedgraph.gz for this purpose?

Many Thanks,
Attila

**Comment by AliciaSchep** [comment]
Sorry didn't see that there was a follow up question; for anyone looking at issue in future, yes either .occ.bedgraph.gz or .nucleoatac_signal.bedgraph.gz could be used for this.  Nucleoatac signal will be higher resolution for positioning information, but is hard to compare between samples due to read depth dependence, so generally for comparing between sample I recommend .occ.bedgraph.gz
