### ISSUE TITLE
NucleoATAC on a whole genome

### ISSUE THREAD

**Issue by PFRoux** [GreenleafLab/NucleoATAC#29]
Dear Alicia,

In the NucleoATAC paper, you describe a comparison of nucleosome positioning across species. However it is not that clear whether you focus on regions with global enrichment in ATAC signal (detected with MACS for instance) or if you screen the entire genome before comparing.

Since you describe here the results obtained when looking at the linker length distribution (distance between adjacent calls), I assumed you performed an untargeted screen to position nucleosomes genome-wide, to be sure not to miss too many calls. Nevertheless, it is required to provide a .bed file to be able to run "nucleoatac run" or "nucleoatac occ" commands. So I am not sure to properly understand what you've done here in your study.

Could you please briefly explain the approach you used for this specific analysis ?

I am sorry if the question sounds quite naive. 

Thanks a lot for your help.

Pierre-François

**Comment by AliciaSchep** [comment]
Hi Pierre-François,

All the analyses in the Genome Res. paper were limited to open chromatin regions (broad peaks determined with MACS2 on ATAC-seq data).  So the linker-length comparison is for linkers within these regions.  Linker length could very well be different in other parts of the genome, but ATAC-seq is not going to be very informative in those other regions due to the sparsity of the data and low signal to noise.  

Hope that addresses your question,
Alicia

**Comment by PFRoux** [comment]
Hi Alicia,

Thanks a lot for this specification.

Cheers and happy new year.

Pierre-François
