### ISSUE TITLE
Insertions and coverage tracks

### ISSUE THREAD

**Issue by DoaneAS** [GreenleafLab/NucleoATAC#39]
Hi,
Thanks for these tools, they are very useful!

Just a few quick questions I couldn't find in the documentation.  

For the insertion frequencies, returned form `pyatac ins`
are these values normalised to total number of insertions?  The documentation says frequencies, but it's not clear to me what the denominator is.

likewise for `pyatac cov`, are the values normalised to total number of fragments in the bam file?

thanks

Ashley

**Comment by AliciaSchep** [comment]
The values are not normalized to the total number of fragments in the bam files.  I think that for the ins the value should just be the per base integer counts (unless smoothed).  For the cov the scaling is fragment centers within a window divided by the window size, multiplied by an arbitrary scaling factor that can be chosen (default is 10, meaning the value is equivalent to fragment centers per 10 bp).  You could make this scaling factor related to the total read count if you want to normalize by that

**Comment by DoaneAS** [comment]
Thanks for explaining and for the helpful suggestion.  I have been using the smoothed ins tracks (using a window of 121) as an alternative to typical coverage tracks (from macs2 output for example), so that the insertion sits are more faithfully represented.  I would be curious to know what you recommend for atac insertion density tracks to represent accessibility.

So if I understand the output of cov correct,  "fragment centers" means the position centered between the Tn5 insertion sites?

Thanks!

**Comment by AliciaSchep** [comment]
Yes the fragment centers means the position that is halfway between the Tn5 insertion sites. This is more similar to a typical coverage plot in which you would consider the contribution of an entire fragment, except that for every fragment a set number of bases around the center contribute to the coverage rather than the whole fragment.    

 I agree with you that for representing accessibility that the smoothed insertion track makes mores sense than either the typical coverage plot or the modified coverage plot computed by "cov",  as it is really the insertion points and not the middle of some fragment that represents the regions that are accessible.

**Comment by DoaneAS** [comment]
Many thanks Alicia!
