### ISSUE TITLE
nucleoATAC applied to MNase 

### ISSUE THREAD

**Issue by uschwartz** [GreenleafLab/NucleoATAC#41]
Dear Alicia,

I would like to use nucleoATAC for MNase-seq data as shown in your publication. Since this is not the standard way, what should be considered and which options have to be changed?

1) How can I turn off the sequence bias model  (as mentioned in your publication)? I created a pwm file with weight 1 on each position. Is that ok?

2) I tried to run the nucleoATAC script on MNase-seq data around CTCF sites (+/- 2500 bp flanking sites), where I observe nicely positioned nucleosomes. However, the nucleoatac nuc script always generates the same error:

Command run:  /home/newadmin/nucleoATAC/bin/nucleoatac nuc --bed data/chr5.dupl.ctcf.mapp.20kb.merge.bed --vmat ctcf_dupl_ext/vprocess.VMat --bam data/high_r1_chr5.bam --out ctcf_dupl_ext/nuc/high --fasta data/chr5.fa --sizes ctcf_dupl_ext/high.fragmentsizes.txt --occ_track ctcf_dupl_ext/high.occ.bedgraph.gz --cores 12 --not_atac --pwm ../pwm.PWM_std.txt
nucleoatac version 0.3.2
start run at: 2016-07-26 11:52
---------Obtaining nucleosome signal and calling positions----------------------
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: divide by zero encountered in log
  nuc_lik = np.sum(np.log(nuc_model) \* mat)
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: invalid value encountered in multiply
  nuc_lik = np.sum(np.log(nuc_model) \* mat)
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:121: RuntimeWarning: divide by zero encountered in log
  null_lik = np.sum(np.log(null_model) \* mat)
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:121: RuntimeWarning: invalid value encountered in multiply
  null_lik = np.sum(np.log(null_model) \* mat)
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: divide by zero encountered in log
  nuc_lik = np.sum(np.log(nuc_model) \* mat)
/home/newadmin/nucleoATAC/local/lib/python2.7/site-packages/nucleoatac/NucleosomeCalling.py:120: RuntimeWarning: invalid value encountered in multiply

...

therefore the output file ...nucpos.bed is always empty.

I already checked that I obtain reads in MNase-seq experiments at the sites I looked for. Do you have an idea how I can solve this issue?

thanks in advance
Uwe

**Comment by AliciaSchep** [comment]
A couple of comments:

1) What is the vplot you are using?  The vmat argument ?  The default V-plot that is included in the package is based on ATAC-seq data-- a very different pattern would be expected for MNase data, and the normalization for fragment size differences between samples that is done in vprocess would not be able to take into account differences between ATAC and MNase

2) Please see Supplementary Figure 11 in the paper.  Looking at different MNase data sets, I observed that the V-plot pattern observed at nucleosome differed greatly between data sets, likely due to differences in digestion (MNase is a processive enzyme, unlike Tn5, so the pattern will be sensitive to the digestion time & concentration).  In contrast, with ATAC-seq I looked at samples prepped with different protocols and different numbers of cells and saw very little difference in the pattern observed (again consistent with Tn5 not being processive).  I could share with you the V-plot used for the MNase analysis paper if you want, but it might not be appropriate for your sample.  For this reason, I generally wouldn't recommend NucleoATAC for use with MNase data.  

3) The data must be paired end for any of the nucleoatac or pyatac functions to work.  I don't think it actually checks for that though, so it could just run and fail quietly or a mystery error. 

4) What is the occ track input?  Was that computed using the nucleoatac occ function?  Because that probably won't work well for MNase data, especially if it is size selected.  

5) Not giving a fasta file as input will turn the bias model off

**Comment by uschwartz** [comment]
Thanks for the quick reply! 
I want to compare two MNase conditions (high and low concentrations) similar to the publication of Henikoff et al, 2011. In the low MNase condition I observe a similar profile at DNase HS sites as seen in ATAC-seq. Therefore, I would like to use nucleoATAC to distinguish between bound tf and nucleosomes. For example directly at CTCF sites shorter fragments accumulate, which are flanked by a population of nucleosomal sized fragments. 

to 1) / 2) I calculated the vplot directly from my MNase data with the nucleoatac vprocess function based on the fragment sizes obtained by nucleoatac occ function. the files are attached
[high_MNase.VMat.pdf](https://github.com/GreenleafLab/NucleoATAC/files/386379/high_MNase.VMat.pdf)
[low_MNase.VMat.pdf](https://github.com/GreenleafLab/NucleoATAC/files/386381/low_MNase.VMat.pdf)
they look quite similar to the v-plots shown in Supplementary figure 11. Are the VMats generated from nucleoATAC vprocess function normalized to the default ATAC-seq V-plot???

to 3) my data is paired-end

to 4) I applied the nucleoATAC occ function to my MNase data and used that for the nuc function as input. The occ script seemed to work fine and I got reasonable output here. The size range for my data is from 50bp-250bp and I did not do a size selection for nucleoATAC.

The only thing that did not work are the nucleosome dyad calls and the file .nucpos.bed.gz is empty.
![nucleoatac_output_snapshot](https://cloud.githubusercontent.com/assets/8363228/17180895/44251fa4-541e-11e6-9e0e-51853159758e.png)

I guess somewhere the "null_model" varible gets zero and this makes problems as it is in the log function, which is reported by the run error:

> _RuntimeWarning: divide by zero encountered in log
> null_lik = np.sum(np.log(null_model) \* mat)_

Would it help to increase the step size in nucleoatac occ function to get rid of this problem?

**Comment by AliciaSchep** [comment]
The nucleoatac vprocess function will use the default ATAC-seq vplot and then adjust based on the fragment sizes -- the pattern there shouldn't work very well for MNase data. The runtime warning should just be a warning and not cause an error.  I suspect that there are no nucleosome calls simply because the v-plot being used doesn't match the data all that well.   I've attached the vplot from the MNase yeast data set used in the paper-- that can be inputted as --vmat to nucleoatac vprocess.  
[Widom.HighRatio.mappable.high_occ.Cole.normdup.VMat.txt](https://github.com/GreenleafLab/NucleoATAC/files/414589/Widom.HighRatio.mappable.high_occ.Cole.normdup.VMat.txt)  (You might have to change the file ending from .txt to .VMat, I had to add the .txt so that github would accept it).  Perhaps you can try with that and see results?

**Comment by uschwartz** [comment]
thanks for providing the the MNase yeast data set. Unfortunately with this normalisation I wont get nucleosome calls as well. As you already mentioned, I guess it is a problem with the MNase, that the v-plots differ quite a lot in various data sets and it has to be adjusted for each MNase digestion. 

Finally I used well positioned nucleosomes around ctcf sites to infer the V-plot pattern for the MNase digestions. Now I get nucleosome calls, but it seems the resolution is not that good. I try to come along with this. 

thanks for your help
