### ISSUE TITLE
Occupancy plot: observed and fitted occupancy differ

### ISSUE THREAD

**Issue by ShaluJhanwar** [GreenleafLab/NucleoATAC#44]
Hi Alicia,

I am running NucleoATAC to identify nucleosome from ATAC-seq data. I looked at the *occ_fit.eps  plot given by NucleoATAC. The observed and nucleosome fit is really different as shown in the plot: 
[nuc_dist](https://www.dropbox.com/s/0hcw5xdl0ec1sts/AllSamplesATAC.nuc_dist.eps?dl=0)
[occ_fit](https://www.dropbox.com/s/uyn857cmxt30al6/AllSamplesATAC.occ_fit.eps?dl=0)
[Vplot](https://www.dropbox.com/s/yex5g17426fduef/AllSamplesATAC.VMat.eps?dl=0)

i) I wonder it is not fitting properly on the observed data. Could you please suggest to tune some parameter to make fitting properly on the observed data? I have pooled the 16 ATAC samples and run nucleoatac run command with default params.

ii) I found approximately 511590 nucleosomes and only 5278 nfr regions as a result of above fitting. Do you think it's correct estimate for numbers of nucpos and nfr region in mouse genome, and positions as well?

Thanks!
Shalu

**Comment by ShaluJhanwar** [comment]
Hi Alicia,

In addition to above details, the global fragment size distribution of one of the 16 samples looks like: [globalfragmentSizeOneSample](https://www.dropbox.com/s/wsywwcjycm6bt2p/globalfragmentsizeOneSample.png?dl=0)

Shalu

**Comment by AliciaSchep** [comment]
The fitting is a bit tricky here because there seems to be a big overlap between NFR and nucleosome distributions (not a clear separation between those two peaks).  Seems to be doing something reasonable given the distribution though

As for the numbers, two things to keep in mind:

1) The nucleosome calling should not be considered comprehensive -- the goal is to find positions where there is evidence of nucleosome positioning from ATAC, but ATAC will not provide adequate coverage when linkers are not very accessible (restricting analysis to peaks helps, but even within the peak regions there may be insufficient coverage throughout).

2) The NFR calling is finding NFR regions bounded by two called nucleosomes and is thus subject to the limitations in (1).  In a development branch of NucleoATAC (NFR) this limitation is limited so that NFRs can be called even when we can't confidently call flanking nucleosomes.
