### ISSUE TITLE
question about output files

### ISSUE THREAD

**Issue by duyphamuab** [GreenleafLab/NucleoATAC#7]
Hi, 
Is occ.bedgraph a combination of lower and uper_bound.bedgraph? 
What is the different between occ.bedgraph vs nucleoatac_signal.bedgraph? 
Thanks, 
Duy

**Comment by AliciaSchep** [comment]
The upper and lower are estimates of the lower bound and upper bound for the nucleosome occupancy based on the number of reads and the model used.  This doesn't take into account systematic biases though so that should be taken into account when interpreting those tracks.  If the upper and lower bound are far apart though that is an indication that there probably weren't enough reads at that locus to make a very meaningful prediction about the occupancy.

The occ.bedgraph is an estimate of nucleosome occupancy using the mixture of fragment sizes.  It does not provide high-resolution position on information though.  In contrast, the nucleoatac_signal is based on our cross-correlation algorithm and gives higher resolution positioning information.  However, as this signal is dependent on the number of ATAC-seq fragments, which is correlated with the accessibility of the locus (especially the linkers) rather than the nucleosome occupancy, this signal does not provide a very good measure of nucleosome occupancy.   

Hope this helps clarify!

**Comment by duyphamuab** [comment]
Hi Alicia, 
Thanks for your answer! I have another question: When you made figure 4d, 6a and 6d in your paper, which information did you use (occ or nucleoatac_signal)?

**Comment by AliciaSchep** [comment]
in the biorxiv v1 paper, 4c is made using nucleoatac_signal,  6a is positions of dyad calls relative to CTCF, 6d is using occ.

In general, the occupancy track is easier to compare across loci or samples as it is always between 0 and 1 and shouldn't depend much on read depth (although will potentially be unreliable outside of open chromatin regions due to low signal to noise in those regions).  However, that track is smoother so either the nucleoatac_signal or the positions of dyad calls can be more useful for when one is interested in more precise nucleosome positioning information

**Comment by duyphamuab** [comment]
Great! Thank you :)
